apiVersion: v1
kind: Service
metadata:
  name: socks-service
spec:
  selector:
    app: socks   # must match Pod labels
  ports:
    - protocol: TCP
      port: 80        # service port
      targetPort: 1080 # container port
  type: ClusterIP